version: "3.3"

services:

  postgres:
    image: postgres:14.2
    environment:
      POSTGRES_USER: zeeshanaslam
      POSTGRES_PASSWORD: postgres
    ports: 
      - '5432:5432'
    volumes:
      - myapp-postgres:/var/lib/postgresql/data

  redis:
    image: redis:7.0
    ports:
      - '6379:6379'
    volumes:
      - myapp-redis:/var/lib/redis/data

  myapp:
    image: $DOCKER_USERNAME/dockerize-rails-myapp:latest
    links:
      - postgres
      - redis
    ports:
      - '8010:8010'
    env_file:
      - .env

  sidekiq:
    image: $DOCKER_USERNAME/dockerize-rails-myapp:latest
    command: bundle exec sidekiq 
    links:
      - postgres
      - redis
    env_file:
      - .env

  nginx:
    image: $DOCKER_USERNAME/dockerize-rails-nginx:latest
    links:
      - myapp
    ports:
      - '8020:8020'

volumes:
  myapp-postgres:
  myapp-redis: